### ISSUE TITLE
caesarcipher file is missing. Please upload that if you have. will be helpful.

### ISSUE THREAD

**Issue by ankitdutta318** [ConanKapoor/Basic-Digital-Envelope#1]

**Comment by ConanKapoor** [comment]
Hey, @cruxbreaker ! Sorry but I never got to the point of updating requirements for the project. It's a python package so you just gotta write this in the terminal - 

`pip3 install caesarcipher`

or if you're using Python2 - 

`pip install caesarcipher`

Thank you for pointing the problem out. I'll update the repo soon :)
If you liked the project, star it. Cheers!
